### PR TITLE
Fix project compliance

### LINKED ISSUE #113: 6.2 Project Compliance Fixes
Noted in https://github.com/BHoM/CarbonQueryDatabase_Toolkit/pull/109/checks?check_run_id=14442454438

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes #113

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check project-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot fix project file ref. 14745437761

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Review by desaiwangBH — APPROVED** [review]
Check compliance is passing, so I approve.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
