### PR TITLE
Removed methods not included in the toolkit

### PR DESCRIPTION
**Pull request by Tom-Kingstone**
### Issues addressed by this PR

Closes #

removed these files as they were causing compliance issues, and weren't included in the solution on compile anyway, so were unusable when the toolkit was compiled.

### CODE REVIEW

**Comment by Tom-Kingstone** [comment]
@BHoMBot check core
@BHoMBot check compliance

**Review by FraserGreenroyd — APPROVED** [review]
Looks good, nice and tidy, thanks @Tom-Kingstone

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

**Comment by Tom-Kingstone** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
