### PR TITLE
Remove API Token method for Security

### LINKED ISSUE #110: Security issue - component taking passwords
Components shouldn't take in a users password which might be inadvertently shared when sharing scripts. The API function should be used instead.

Step required to remove and version the option taking in passwords.

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes #110

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot fix project file ref. 14322567065

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Review by travispotterBH — APPROVED** [review]
Changes make sense, doesn't appear to break functionality. 👍

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core
@BHoMBot check null-handling
@BHoMBot check serialisation
@BHoMBot check ready-to-merge

**Pull request merged**
