### PR TITLE
Fix lifespan datatype

### LINKED ISSUE #131: Using NameLike produces an error
#### Description:

Error found in connection with the `ToBHoM` method when adding the `lifespan` property to the `ClimateChangeMetric`. Seems there's an invalid cast that causes an error, but somehow is only triggered when using the `NameLike` param. 

I still need to do some digging on this error.

### PR DESCRIPTION
**Pull request by michaelhoehn**
### Issues addressed by this PR

Closes #131 

### Test files

[Test file](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/CarbonQueryDatabase_Toolkit/CarbonQueryDatabase_Toolkit-%23131-NameLike-bug/CarbonQueryDatabase_Toolkit-%23131-NameLike-bug.gh?csf=1&web=1&e=qbBg1M)

### CODE REVIEW

**Review by enarhi — APPROVED** [review]
LGTM, used test script and was able to successfully pull EPD's from EC3 using the NameLike filter.

**Comment by michaelhoehn** [comment]
@BHoMBot check required

**Comment by michaelhoehn** [comment]
@BHoMBot check copyright-compliance

**Comment by michaelhoehn** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
